In [ ]:
import pandas as pd ## 1.0.3
import numpy as np ## 1.18.2

import warnings
warnings.filterwarnings('ignore')

In [2]:
np.__version__

'1.19.2'

In [ ]:
np.random.seed(12345)

In [ ]:
df_pima = pd.read_csv('pima-indians-diabetes.csv')

In [4]:
df_pima.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
df_pima.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [12]:
#X=df_pima.drop(['Outcome'],axis=1)
#y=df_pima[['Outcome']]
X=df_pima.drop(['Outcome'],axis=1)
y=df_pima['Outcome']

In [14]:
y.shape

(768,)

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 48.1 KB


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test, y_train,y_test = train_test_split(X,
                                                  y, 
                                                  train_size = 0.75,
                                                  random_state=12345)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [18]:
X_train_scaled =scaler.fit_transform(X_train) #scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)#transform(X_test)

In [23]:
X_train_scaled[0]

array([ 1.19392448, -0.08038457,  0.85610434, -1.27065328, -0.67776133,
       -0.44516113, -0.63585204, -0.98661561])

In [24]:
#from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [25]:
dtree = DecisionTreeClassifier(random_state=12345)
dtree.fit(X_train,y_train)

DecisionTreeClassifier(random_state=12345)

In [26]:
y_pred_sc=dtree.predict(X_test_scaled)

In [27]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [37]:
a1=confusion_matrix(y_pred=y_pred_sc,y_true=y_test)

In [38]:
a1

array([[132,   0],
       [ 60,   0]], dtype=int64)

In [42]:
np.diagonal(confusion_matrix(y_pred=y_pred_sc,y_true=y_test)).sum()/192*100

68.75

In [40]:
accuracy_score(y_pred=dtree.predict(X_test_scaled),y_true=y_test)*100

68.75

In [49]:
accuracy_score(y_pred=dtree.predict(X_train_scaled),y_true=y_train)

0.6388888888888888

In [2]:
#from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
import numpy as np
square=lambda x:x*x
p1=[1.,3.]
p2=[2.,5.]

euclidean_distance=square((p1[0]-p2[0]**2)+(p1[1]-p2[1]**2))
print(euclidean_distance)

625.0


In [4]:
rf_model = RandomForestClassifier(random_state=12345)
rf_model.fit(X_train,y_train)

NameError: name 'X_train' is not defined

In [ ]:
confusion_matrix(y_pred = rf_model.predict(X_test_scaled),y_true = y_test)

In [ ]:
accuracy_score(y_pred = rf_model.predict(X_test_scaled),y_true = y_test)

In [48]:

accuracy_score(y_pred = rf_model.predict(X_train_scaled),y_true = y_train)

0.6388888888888888

In [54]:
import sklearn
print(sklearn.__version__)

1.0.1


In [55]:
np.__version__

'1.19.2'

In [49]:
#from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

In [50]:
ada_model = AdaBoostClassifier(random_state=12345)
ada_model.fit(X_train_scaled,y_train)

AdaBoostClassifier(random_state=12345)

In [52]:
confusion_matrix(y_pred = ada_model.predict(X_test_scaled),y_true = y_test)

array([[115,  17],
       [ 25,  35]], dtype=int64)

In [53]:
accuracy_score(y_pred = ada_model.predict(X_test_scaled),y_true = y_test)

0.78125

In [54]:
#from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [55]:
gbm_model = GradientBoostingClassifier(random_state=12345)
gbm_model.fit(X_train_scaled, y_train)

GradientBoostingClassifier(random_state=12345)

In [56]:
gbm_pred = gbm_model.predict(X_test_scaled)

In [58]:
confusion_matrix(y_pred = gbm_pred, y_true=y_test)

array([[118,  14],
       [ 24,  36]], dtype=int64)

In [59]:
accuracy_score(y_pred = gbm_pred, y_true=y_test)

0.8020833333333334

In [60]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [64]:
#from xgboost import XGBClassifier
from  xgboost import XGBClassifier

In [65]:
import xgboost
xgboost.__version__

'1.5.0'

In [67]:
#xgb_model = XGBClassifier(random_state = 12345, learning_rate = 0.017)
#xgb_model.fit(X_train_scaled, y_train)
xgb_model=XGBClassifier(random_state=12345,learning_rate=0.017)
xgb_model.fit(X_train,y_train)

[20:52:54] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.017, max_delta_step=0,
              max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=2,
              num_parallel_tree=1, predictor='auto', random_state=12345,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [71]:
xgb_pred = xgb_model.predict(X_test_scaled)

In [72]:
confusion_matrix(y_pred = xgb_pred, y_true=y_test)

array([[132,   0],
       [ 60,   0]], dtype=int64)

In [73]:
accuracy_score(y_pred = xgb_pred, y_true=y_test)

0.6875

In [75]:
#from sklearn.model_selection import KFold, cross_val_score
from sklearn.model_selection import KFold,cross_val_score

In [78]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_scaled = scaler.fit_transform(X)

In [82]:
from sklearn.ensemble import RandomForestClassifier
kfold_model = KFold(n_splits=10)
krfc_model = RandomForestClassifier(random_state=12345)
results = cross_val_score(krfc_model, X, y, cv=kfold_model)

In [84]:
print(results)

[0.67532468 0.85714286 0.74025974 0.64935065 0.77922078 0.80519481
 0.84415584 0.87012987 0.69736842 0.78947368]


In [85]:
X.shape

(768, 8)

In [34]:
int(768/5)

153

In [70]:
results

array([0.67532468, 0.85714286, 0.74025974, 0.64935065, 0.77922078,
       0.80519481, 0.84415584, 0.87012987, 0.69736842, 0.78947368])

In [86]:
results.mean()

0.770762132604238

In [87]:
from sklearn.model_selection import LeaveOneOut
leaveoo = LeaveOneOut()

In [88]:
for train,test in leaveoo.split(X):
    print(X.iloc[train[0:3],:])
    print(X.iloc[test[0],:])
    break

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   

   DiabetesPedigreeFunction  Age  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
Pregnancies                   6.000
Glucose                     148.000
BloodPressure                72.000
SkinThickness                35.000
Insulin                       0.000
BMI                          33.600
DiabetesPedigreeFunction      0.627
Age                          50.000
Name: 0, dtype: float64
